#!/usr/bin/env bash

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Shortcuts
alias a="atom"
alias e="$EDITOR"
alias g="git"
alias v="vim"
alias c="clear"
alias h="history"

alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias gh="cd ~/github/thibault"
alias log="cd /var/log"

# Default options
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias rr="rm -rf"
alias mkdir="mkdir -pv"
alias ll="ls -FGlahp"
alias ps="ps -ef"
alias less="less -FSRXc"
alias grep='grep --color=auto'

# Git
alias git=hub

alias gs="git status -s"        # pretty status
alias gp="git pull"
alias gc="git checkout"         # switch to branch, -b to create one on the fly
alias ga="git add -p"           # step through each change, or hunk
alias gc="git commit"
alias gpu="git push origin HEAD"
alias gpr="git pull-request"

alias gl="git log --all --graph --decorate --oneline --simplify-by-decoration"
alias gd="git diff --color | diff-so-fancy | less --tabs=4 -RFX"
alias gf="git reflog"           # see every step made with git
alias gcln="git clean -xfd"     # remove untracked files

alias wip="git commit -m "wip" . && git push origin HEAD"

# Edit ~/.bash_profile and /etc/hosts file
alias edith="sudo $EDITOR /etc/hosts"
alias editbp="$EDITOR ~/.bash_profile"

# Node, CoffeeScript and NPM shortcuts
alias npmls="npm -g ls --depth=0"
alias buny="coffee index.coffee | bunyan"

# Better tree
alias tree="tree -aCF --dirsfirst -I '.git|node_modules'"

# Print each PATH entry on a separate line
alias path="echo -e ${PATH//:/\\n}"

# Always copy pwd
alias pwd="pwd|tr -d "\n"|pbcopy"

# Reload the shell
alias reload="exec $SHELL -l"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

# Lock the screen
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Flush Directory Service cache
alias flush="sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Pull all the Git repositories
alias pullall="gh && find . -maxdepth 1 -type d -exec sh -c '(cd {} && git pull)' ';'"

# Get Mac OS software updates, update Homebrew, NPM and their packages
alias update="sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; brew doctor; npm install npm -g; npm update -g"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"
