#!/usr/bin/env bash

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias dc="cd ~/Documents"
alias gh="cd ~/github"

alias cd-log="cd /var/log"

# Shortcuts
alias e="emacs &"
alias g="git"
alias c="clear"
alias h="history"

# Default options
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias rr="rm -rf"
alias mkdir="mkdir -pv"
alias ll="ls -FGlahp"
alias ps="ps -ef"
alias less="less -FSRXc"
alias grep='grep --color=auto'

# Git
alias git=hub

# Edit ~/.bash_profile and /etc/hosts file
alias edith="sudo $EDITOR /etc/hosts"
alias editbp="$EDITOR ~/.bash_profile"

# Node, CoffeeScript and NPM shortcuts
alias npmls="npm -g ls --depth=0"
alias n="coffee index.coffee | bunyan -o short"
alias nd="node-debug -p 4444 -c true -b false coffee index.coffee | bunyan -o short"

# Docker
alias d="docker"
alias dc="docker-compose"
alias dex="docker exec -it"

# Python
alias pipi="sudo -H pip install -r requirements.txt"

# Better tree
alias tree="tree -aCF --dirsfirst -I '.git|node_modules'"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Always copy pwd
alias pwd="pwd|tr -d "\n"|pbcopy"

# Reload the shell
alias reload="exec $SHELL -l"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

# Lock the screen
alias afk="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"

# Flush Directory Service cache
alias flush="sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Pull all the Git repositories
alias pullall="find . -maxdepth 1 -type d -exec sh -c '(cd {} && git pull)' ';'"

# Homebrew update
alias update="brew update; brew upgrade; brew cleanup; brew doctor"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"
