#!/usr/bin/env bash

# Always list directory contents upon 'cd'
function cd() {
    builtin cd "$@"; ll;
}

# Makes new Dir and jumps inside
function mk() {
    mkdir -p "$@" && cd "$@";
}

# Fuzzy find file
function ff() {
    find . -type f -iname "*$1*";
}

# Fuzzy find directory
function fd() {
    find . -type d -iname "*$1*";
}

# Moves a file to the MacOS trash
function trash () {
    command mv "$@" ~/.Trash ;
}

# Open man page as PDF
function manpdf() {
  man -t "$1" | open -f -a /Applications/Preview.app/
}

# Open query in Dash app
function dash() {
  case $# in
    1) QUERY="$1";;
    2) QUERY="$1:$2";;
    *) echo "Usage: dash [docset] query"; return 1;
  esac
  open "dash://$QUERY"
}

# `a` with no arguments opens the current directory in Atom Editor,
# otherwise opens the given location
function a() {
    if [ $# -eq 0 ]; then
        atom .;
    else
        atom "$@";
    fi;
}

#`v` with no arguments opens the current directory in vim,
# otherwise opens the given location
function v() {
   if [ $# -eq 0 ]; then
       vim .;
   else
       vim "$@";
   fi;
}

# `o` with no arguments opens the current directory,
# otherwise opens the given location
function o() {
    if [ $# -eq 0 ]; then
        open .;
    else
        open "$@";
    fi;
}

# get colors in manual pages
function man() {
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \s
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}

# syntax highligh in cat
function cat() {
    local out colored
    out=$(/bin/cat $@)
    colored=$(echo $out | pygmentize -f console -g 2>/dev/null)
    [[ -n $colored ]] && echo "$colored" || echo "$out"
}
