[aws]
symbol = "  "
style = "yellow"
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"

[directory]
read_only = " "
truncate_to_repo = false
style = "bold blue"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
always_show_remote = true
style = "yellow"

[git_commit]
only_detached = false
tag_disabled = false
style = "yellow"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[git_status]
style = "red"

[golang]
symbol = " "

[line_break]
disabled = false

[java]
symbol = " "

[kubernetes]
disabled = false
style = "cyan"
format = '[$symbol$context( \($namespace\))]($style) in '

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[python]
symbol = " "
python_binary = ["python3"]

[ruby]
symbol = " "

[rust]
symbol = " "

[status]
format = '[\[$symbol $status\]]($style) '
disabled = false

