command_timeout = 5000

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
truncate_to_repo = false
style = "bold blue"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
always_show_remote = true
style = "bold yellow"

[git_commit]
only_detached = false
tag_disabled = false
style = "yellow"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[line_break]
disabled = true

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[status]
format = '[\[$symbol $status\]]($style) '
disabled = false

[swift]
symbol = "ﯣ "
