#!/bin/bash

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias dm="cd ~/Documents"

alias gh="cd ~/git"
alias logs="cd /var/log"

# git repos aliases
TL_REPOS_PATH="${HOME}/git/thibault"
REPOS=$(find "$TL_REPOS_PATH" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
for REPO in $REPOS; do
    # shellcheck disable=SC2139
    alias "$REPO"='cd $TL_REPOS_PATH/$REPO'
done

# Shortcuts
alias e="emacs &"
alias g="git"
alias c="clear"
alias h="history"
alias t="tmux"

# Default options
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias rr="rm -rf"
alias mkdir="mkdir -pv"
alias ll='ls -FGlahp --color=always'
alias ps="ps -ef"
alias less="less -FSRXc"
alias grep='grep --color=auto'
alias df="df -Th"
alias du="du -ach | sort -h"

# Git
alias git="hub"

# Htop
alias top="htop"

# Edit ~/.bash_profile and /etc/hosts file
alias edith='sudo $EDITOR /etc/hosts'
alias editbp='$EDITOR ~/.bash_profile'

# Docker
alias d="docker"
alias dc="docker-compose"
alias dex="docker exec -it"

# Better tree
alias tree="tree -aCF --dirsfirst -I '.git|node_modules'"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Reload the shell
alias reload='exec $SHELL -l'

# Pull all the Git repositories
alias pull-all="find . -maxdepth 1 -type d -exec sh -c '(cd {} && git pull)' ';'"

# Go to useful go directory
alias go-git='cd $GOPATH/src/github.com'

# Google drive alias
alias drive="cd ~/drive"

# External IP addresses
alias wanip='dig @resolver1.opendns.com A myip.opendns.com +short -4'
alias wanip6='dig @resolver1.opendns.com AAAA myip.opendns.com +short -6'
