#!/bin/bash

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Quick cd
alias dl="cd ~/Downloads"
alias dm="cd ~/Documents"
alias dr="cd ~/drive"
alias dt="cd ~/Desktop"
alias gh="cd ~/git"
alias ghgo='cd $GOPATH/src/github.com'
alias lg="cd /var/log"

# git repos aliases
REPOS=$(find "$GIT_REPOS" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
for REPO in $REPOS; do
    # shellcheck disable=SC2139
    alias "$REPO=cd $GIT_REPOS/$REPO"
done

# Default options
alias cp="cp -iv"
alias df="df -Th"
alias du="du -ach | sort -h"
alias grep='grep --color=auto'
alias less="less -FSRXc"
alias ll='ls -FGlahp --color=always'
alias mkdir="mkdir -pv"
alias ps="ps -ef"
alias rm="rm -Iv"
alias rr="rm -rf"
alias tree="tree -aCF --dirsfirst -I '.git|node_modules'"

# Shortcuts
alias c="clear"
alias dc="docker-compose"
alias dex="docker exec -it"
alias git="hub"
alias h="history"
alias t="tmux"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Reload the shell
alias reload='exec $SHELL -l'

# External IP addresses
alias wanip='dig @resolver1.opendns.com A myip.opendns.com +short -4'
alias wanip6='dig @resolver1.opendns.com AAAA myip.opendns.com +short -6'
