#!/usr/bin/env bash

# Proper locale
: ${LANG:="en_US.UTF-8"}
: ${LANGUAGE:="en"}
: ${LC_CTYPE:="en_US.UTF-8"}
: ${LC_ALL:="en_US.UTF-8"}
export LANG LANGUAGE LC_CTYPE LC_ALL

# Make vim the default editor
export EDITOR='vim';

# Ignore duplicate commands and commands that begin with a space in the history
export HISTCONTROL='ignoreboth';

# Allow 32³ lines in the history file, the default is 500
export HISTFILESIZE='32768';

# Allow 32³ commands to remember, the default is 500
export HISTSIZE='32768';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr
export PYTHONIOENCODING='UTF-8';

# Don’t clear the screen after quitting a manual page
PAGER="less -FirSwX"
MANPAGER="$PAGER"
export PAGER MANPAGER

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND";

export CLICOLOR=1

# Always use passive mode FTP
: ${FTP_PASSIVE:=1}
export FTP_PASSIVE

# Set terminal emulator
export TERM=xterm-256color
