name: shell
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.sh"
    branches:
      - "master"
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.8.0
    steps:
      - uses: actions/checkout@v3
      - name: Check shell scripts
        run: shellcheck -e SC1091,SC1090 $HOME/.install/*.sh
